### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by KettuS** [ptrpaws/Among-Us-Trasher#2]
How i can add more buttons etc.

plz help

**Comment by ptrpaws** [comment]
@KettuS I'm sorry for the late reply.
I've made a short video tutorial on how to add a button. The rest is basic C#.NET.
Feel free to ask me more questions

https://user-images.githubusercontent.com/34898868/106398929-0fad3600-6416-11eb-93ac-cda99164ac4b.mp4
